name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
        branches: ["main"]

concurrency:
    group: "cd"
    cancel-in-progress: false

jobs:
    release:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
              with:
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SEMANTIC_RELEASE_SSH_KEY }}
                  persist-credentials: true

            - name: Setup Environment
              id: setup
              uses: ./.github/actions/setup-env

            - name: Build Artifacts
              run: bun run build

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: bun x --bun semantic-release
